In [1]:
from numpy import loadtxt
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

ModuleNotFoundError: No module named 'keras'

In [ ]:
#Load the dtaset using pandas
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv')
df.to_csv('pima.csv')

#Use one of this
import requests

response = requests.get('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv')

with open('pima_r.csv', 'w+') as file:
  file.write(response.text)

In [ ]:
#load the data( .csv=',' & .tsv='\t')
dataset = loadtxt('/content/pima_r.csv', delimiter=',')
#split
x = dataset[:,0:8]
y = dataset[:,8]

#######

In [ ]:
df_x = np.array(df.iloc[:,0:8].astype(int))
df_y = np.array(df.iloc[:,8].astype(int))

In [ ]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
df_x

array([[  1,  85,  66, ...,  26,   0,  31],
       [  8, 183,  64, ...,  23,   0,  32],
       [  1,  89,  66, ...,  28,   0,  21],
       ...,
       [  5, 121,  72, ...,  26,   0,  30],
       [  1, 126,  60, ...,  30,   0,  47],
       [  1,  93,  70, ...,  30,   0,  23]])

In [ ]:
x[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [ ]:
#Dfine the keras model
model = Sequential()
model.add(Dense(12, input_shape=(8,),activation='relu')) #Input Layers
#hidden Layers
model.add(Dense(8, activation='relu'))
model.add(Dense(6, activation='relu'))
#End of hidden layer
model.add(Dense(1, activation='sigmoid')) #Output layer

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x, y, epochs=150, batch_size=10)

In [ ]:
_, accuracy = model.evaluate(x, y)
print(accuracy)

24/24 [==============================] - 0s 1ms/step - loss: 0.4382 - accuracy: 0.7943
0.7942708134651184
